# Generated by Django 5.1.5 on 2025-01-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='URLAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='shortener.shortenedurl')),
            ],
            options={
                'verbose_name_plural': 'URL accesses',
            },
        ),
    ]
